"""Markdown report templates."""

from __future__ import annotations


def daily_report_template(
    date: str,
    brief: str,
    dart_items: list,
    news_items: list,
    market_close: bool = False,
) -> str:
    edition = "장 마감" if market_close else "일일"
    lines = [f"# {edition} 시장 리포트 ({date})\n"]
    lines.append(brief)
    lines.append("")

    if dart_items:
        lines.append("\n---\n## 수집된 공시\n")
        for item in dart_items[:20]:
            corp = item.metadata.get("corp_name", "")
            lines.append(f"- [{corp} | {item.title}]({item.url})")

    if news_items:
        lines.append("\n---\n## 수집된 뉴스\n")
        for item in news_items[:20]:
            lines.append(f"- [{item.title}]({item.url})")

    lines.append(f"\n---\n*Generated by kubera-intel*\n")
    return "\n".join(lines)


def stock_report_template(
    code: str,
    name: str,
    date: str,
    summary: str,
    sentiment: str,
    key_points: list[str],
    items: list,
) -> str:
    label = f"{name} ({code})" if name else code
    sentiment_emoji = {"positive": "+", "negative": "-", "neutral": "~"}.get(sentiment, "~")

    lines = [f"# {label} 심층 분석 ({date})\n"]
    lines.append(f"**Sentiment: [{sentiment_emoji}] {sentiment}**\n")
    lines.append("## 요약\n")
    lines.append(summary)
    lines.append("")

    if key_points:
        lines.append("## 핵심 포인트\n")
        for point in key_points:
            lines.append(f"- {point}")
        lines.append("")

    if items:
        lines.append("---\n## 관련 자료\n")
        for item in items[:20]:
            lines.append(f"- [{item.source}] [{item.title}]({item.url})")

    lines.append(f"\n---\n*Generated by kubera-intel*\n")
    return "\n".join(lines)
